(() => {
  const svg = document.querySelector("#w4-canvas"), q = document.querySelector("#w4-q"), status = document.querySelector("#w4-status");
  const base = [{id:"A",x:120,y:120,c:0},{id:"B",x:220,y:75,c:0},{id:"C",x:320,y:130,c:0},{id:"D",x:220,y:250,c:1},{id:"E",x:430,y:90,c:1},{id:"F",x:550,y:155,c:1},{id:"G",x:470,y:280,c:1},{id:"H",x:610,y:285,c:1}];
  const edges=[["A","B",2],["B","C",2],["A","C",1],["B","D",1],["C","D",1],["D","E",1],["E","F",2],["F","G",2],["G","H",2],["F","H",1]];
  let nodes=JSON.parse(JSON.stringify(base)), graphEdges=edges.map(edge=>edge.slice()), collapsed=false;
  const color=["#ed784d","#8fc4b1","#e9c46a","#a9b8ee"];
  function modularity(){let m=graphEdges.reduce((s,e)=>s+e[2],0), degrees=new Map(nodes.map(n=>[n.id,0])), internal=new Map(nodes.map(n=>[n.c,0])); if(!m)return 0; graphEdges.forEach(([a,b,w])=>{degrees.set(a,degrees.get(a)+w);degrees.set(b,degrees.get(b)+w); if(nodes.find(n=>n.id===a).c===nodes.find(n=>n.id===b).c)internal.set(nodes.find(n=>n.id===a).c,internal.get(nodes.find(n=>n.id===a).c)+w)}); return [...internal].reduce((sum,[community,weight])=>{let degree=[...nodes].filter(n=>n.c===community).reduce((s,n)=>s+degrees.get(n.id),0);return sum+weight/m-(degree/(2*m))**2},0)}
  function draw(){svg.innerHTML=""; graphEdges.forEach(([a,b])=>{let u=nodes.find(n=>n.id===a),v=nodes.find(n=>n.id===b);if(!u||!v)return;let l=document.createElementNS("http://www.w3.org/2000/svg","line");l.setAttribute("x1",u.x);l.setAttribute("y1",u.y);l.setAttribute("x2",v.x);l.setAttribute("y2",v.y);l.setAttribute("stroke","#b7c7dc");l.setAttribute("stroke-opacity",".5");svg.append(l)});nodes.forEach(n=>{let c=document.createElementNS("http://www.w3.org/2000/svg","circle");c.setAttribute("cx",n.x);c.setAttribute("cy",n.y);c.setAttribute("r",collapsed?28:23);c.setAttribute("fill",color[n.c%color.length]);c.setAttribute("stroke","#fff");c.setAttribute("tabindex","0");c.setAttribute("aria-label",`Community ${n.c+1}, node ${n.id}`);c.addEventListener("click",()=>move(n));c.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();move(n)}});svg.append(c);let t=document.createElementNS("http://www.w3.org/2000/svg","text");t.setAttribute("x",n.x);t.setAttribute("y",n.y+5);t.setAttribute("text-anchor","middle");t.setAttribute("font-family","monospace");t.setAttribute("font-size","14");t.setAttribute("fill","#172a48");t.textContent=n.id;svg.append(t)});q.textContent=modularity().toFixed(3)}
  function move(n){if(collapsed)return;let original=n.c,bestCommunity=original,best=modularity(), candidates=[...new Set(graphEdges.flatMap(e=>e[0]===n.id?[nodes.find(x=>x.id===e[1]).c]:e[1]===n.id?[nodes.find(x=>x.id===e[0]).c]:[]))];candidates.forEach(community=>{n.c=community;let value=modularity();if(value>best+0.001){best=value;bestCommunity=community}});n.c=bestCommunity;status.textContent=`${n.id} ${bestCommunity===original?"stays":"moves"} in community ${n.c+1}.`;draw()}
  document.querySelector("#w4-step").onclick=()=>{let n=nodes.find(x=>x.c===0)||nodes[0];move(n);status.textContent="A greedy local move was attempted."};
  document.querySelector("#w4-aggregate").onclick=()=>{if(collapsed)return;const groups=[...new Set(nodes.map(n=>n.c))], groupId=new Map(groups.map((community,index)=>[community,"C"+(index+1)])), originalNodes=nodes.slice();const aggregated=new Map();graphEdges.forEach(([a,b,w])=>{const source=groupId.get(originalNodes.find(n=>n.id===a).c),target=groupId.get(originalNodes.find(n=>n.id===b).c);if(source===target)return;const key=source<target?`${source}|${target}`:`${target}|${source}`;aggregated.set(key,[source,target,(aggregated.get(key)?.[2]||0)+w])});nodes=groups.map((community,index)=>({id:"C"+(index+1),x:150+index*190,y:190,c:index}));graphEdges=[...aggregated.values()];collapsed=true;status.textContent="Phase two: communities are now super-nodes.";draw()};
  document.querySelector("#w4-reset").onclick=()=>{nodes=JSON.parse(JSON.stringify(base));graphEdges=edges.map(edge=>edge.slice());collapsed=false;status.textContent="Reset.";draw()}; draw();
})();
